import "dotenv/config";
import { getDb } from "./server/db";
import { properties } from "./drizzle/schema";

const seedProperties = [
  {
    name: 'Edificio en San Luis',
    propertyType: 'building' as const,
    price: "3000000000",
    location: 'Bogotá, Teusaquillo',
    zone: 'San Luis',
    bedrooms: 20,
    bathrooms: 15,
    garages: 0,
    yearBuilt: 2024,
    areaTotal: "1068",
    featured: true,
    available: true,
    images: ['https://edificio-teusaquillo-bogota.netlify.app/assets/1.png'],
    description: 'Venta de edificio híbrido en Teusaquillo rentando $18.9M. 4 pisos: local, clínica, oficinas y 20 hab. ideales para Airbnb. Recién remodelado.',
  },
  {
    name: 'Edificio en Santa Bárbara',
    propertyType: 'building' as const,
    price: "18000000000",
    location: 'Bogotá, Usaquén',
    zone: 'Santa Bárbara',
    bedrooms: 26,
    bathrooms: 26,
    garages: 43,
    yearBuilt: 2009,
    areaTotal: "5000",
    featured: true,
    available: true,
    images: ['https://static.wixstatic.com/media/334454_47f092e1f6bc419b8641c50b62c8d482~mv2.jpg'],
    description: 'Edificio completo en venta con 26 apartamentos en Santa Bárbara, Usaquén. 5.000 m² construidos, 43 parqueaderos, amenidades completas.',
  },
  {
    name: 'Edificio en La Castellana',
    propertyType: 'building' as const,
    price: "5000000000",
    location: 'Bogotá, Barrios Unidos',
    zone: 'La Castellana',
    bedrooms: 7,
    bathrooms: 7,
    garages: 9,
    yearBuilt: 2002,
    areaTotal: "871",
    featured: true,
    available: true,
    images: ['https://edificio-castellana-bogota.netlify.app/assets/1.jpg'],
    description: 'Edificio exclusivo en La Castellana, Bogotá. 871 m², 5 pisos, 7 apartamentos independientes incluyendo Pent-house. Ideal inversión.',
  },
  {
    name: 'Hotel en Quinta Paredes',
    propertyType: 'hotel' as const,
    price: "2500000000",
    location: 'Bogotá, Teusaquillo',
    zone: 'Quinta Paredes',
    bedrooms: 14,
    bathrooms: 15,
    garages: 1,
    yearBuilt: 2012,
    areaTotal: "493",
    featured: true,
    available: true,
    images: ['https://hotel-quinta-paredes-bogota.netlify.app/assets/1.1.png'],
    description: 'Hotel Cerca de Corferias: Elegancia y Rentabilidad Estratégica. 14 Habitaciones, Penthouse, Rentabilidad Comprobada.',
  },
  {
    name: 'Casa en La Calleja',
    propertyType: 'house' as const,
    price: "890000000",
    location: 'Bogotá, Usaquén',
    zone: 'La Calleja',
    bedrooms: 3,
    bathrooms: 3,
    garages: 2,
    yearBuilt: 1976,
    areaTotal: "150",
    featured: true,
    available: true,
    images: ['https://casa-la-calleja-bogota.netlify.app/assets/14.jpg'],
    description: 'Casa chalet de 150m² con 3 habitaciones, 3 baños, estudio, terrazas y remodelación integral. Oportunidad única en La Calleja.',
  },
  {
    name: 'Casa en Polo Club',
    propertyType: 'house' as const,
    price: "1250000000",
    location: 'Bogotá, Barrios Unidos',
    zone: 'Polo Club',
    bedrooms: 5,
    bathrooms: 4,
    garages: 3,
    yearBuilt: 1986,
    areaTotal: "205",
    featured: true,
    available: true,
    images: ['https://casa-polo-club-bogota.netlify.app/assets/1.jpg'],
    description: 'Excelente oportunidad. Casa de 204.79 m² en el barrio Polo Club, Bogotá. 5 habitaciones, 4 baños, 3 parqueaderos, patio automatizado.',
  },
  {
    name: 'Apartamento en Cedritos',
    propertyType: 'apartment' as const,
    price: "1300000000",
    location: 'Bogotá, Usaquén',
    zone: 'Cedritos',
    bedrooms: 3,
    bathrooms: 4,
    garages: 2,
    yearBuilt: 2026,
    areaTotal: "152",
    featured: true,
    available: true,
    images: ['https://ap-nuevo-cedritos-bog.netlify.app/assets/portada_video_fotos_redes_enlaces.png'],
    description: '¡Oportunidad única! 151.70m² + Terraza Privada 84m². 3 Hab c/u con baño. Proyecto premium en Cedritos.',
  },
  {
    name: 'Apartamento en Floridablanca',
    propertyType: 'apartment' as const,
    price: "500000000",
    location: 'Bucaramanga, Santander',
    zone: 'Floridablanca',
    bedrooms: 3,
    bathrooms: 2,
    garages: 1,
    yearBuilt: 2014,
    areaTotal: "130",
    featured: true,
    available: true,
    images: ['https://apartamento-bumanga-santander.netlify.app/assets/3.jpeg'],
    description: 'Espectacular apartamento de 130m² en Floridablanca. Terraza Privada, 3 Alcobas y Club House. Permuta 50/50 Bogotá.',
  },
  {
    name: 'Apartamento en San Patricio',
    propertyType: 'apartment' as const,
    price: "2000000000",
    location: 'Bogotá, Usaquén',
    zone: 'San Patricio',
    bedrooms: 5,
    bathrooms: 5,
    garages: 3,
    yearBuilt: 2004,
    areaTotal: "243",
    featured: true,
    available: true,
    images: ['https://apto-san-patricio-bog.netlify.app/assets/1.jpg'],
    description: 'Apartamento en San Patricio Bogotá - $2.000 Millones - 243m² - 5 Habitaciones - 5 Baños - 3 Garajes - Estrato 6. Exclusividad.',
  },
];

async function seed() {
  const db = await getDb();
  if (!db) {
    console.error("No database connection");
    return;
  }
  console.log("Seeding properties...");
  for (const prop of seedProperties) {
    await db.insert(properties).values(prop);
  }
  console.log("Seeding complete!");
  process.exit(0);
}

seed().catch(console.error);
